modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Altnoir/PoopSkyMod"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# 前置：PoopSky（required 保证 PoopSky 先于本模组加载）
[[dependencies.${mod_id}]]
modId = "poopsky"
type = "required"
versionRange = "[2.2,)"
ordering = "AFTER"
side = "BOTH"

# 前置库：AbyssLib（提供 Registrate / SBM 运行时与 ALRegistrate）
[[dependencies.${mod_id}]]
modId = "abysslib"
type = "required"
versionRange = "[1.1,)"
ordering = "AFTER"
side = "BOTH"
